[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "picotool load -u -v -x -t elf"

rustflags = [
 "-C", "link-arg=--nmagic",
 "-C", "link-arg=-Tlink.x",
 "-C", "target-cpu=cortex-m33",
]

[build]
#target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+
target = "thumbv8m.main-none-eabihf"      # Cortex-M33

[env]
DEFMT_LOG = "debug"