[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip stm32g431kbtx'
rustflags = [
  "-C", "link-arg=-Tlink.x",
]
# "-C", "link-arg=-Tdefmt.x",

[env]
DEFMT_LOG = "info"

[build]
target = "thumbv7em-none-eabihf"